dist: trusty
sudo: false
language: node_js
node_js:
  - "6.11.2"
install:
  - npm install
script:
  - npm run lint
  - npm run test-cov
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov